Added glyphs to some modules. Restructed config options for modules. Changed defaults to be minimal examples.

diff --git a/pureline b/pureline
--- a/pureline
+++ b/pureline
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Based on: https://github.com/abhijitvalluri/bash-powerline-shell
+# PureLine - A Pure Bash Powerline PS1 Command Prompt 
 
 # -----------------------------------------------------------------------------
 # returns git branch name
@@ -20,11 +20,11 @@ function git_branch_name {
 function section_end {
     if [ "$__last_color" == "$2" ]; then
         # Section colors are the same, use a foreground separator
-        local end_char=""
+        local end_char="${symbols[soft_separator]}"
         local fg=$1
     else
         # section colors are different, use a background separator
-        local end_char=""
+        local end_char="${symbols[hard_separator]}"
         local fg=$__last_color
     fi
     if [ ! -z "$__last_color" ]; then
@@ -61,10 +61,10 @@ function time_module {
 function host_module {
     local bg_color=$1
     local fg_color=$2
-    if [ "$1" = true ]; then
+    if [ "$3" = true ]; then
         local content="\u@\h"
     else
-        local content="\h"
+        local content="${symbols[host]} \h"
     fi
     PS1+=$(section_end $fg_color $bg_color)
     PS1+=$(section_content $fg_color $bg_color " $content ")
@@ -79,7 +79,7 @@ function path_module {
     local bg_color=$1
     local fg_color=$2
     PS1+=$(section_end $fg_color $bg_color)
-    PS1+=$(section_content $fg_color $bg_color " \W ")
+    PS1+=$(section_content $fg_color $bg_color " ${symbols[folder]} \W ")
     __last_color=$bg_color
 }
 
@@ -93,7 +93,7 @@ function jobs_module {
     local number_jobs=$(jobs -p | wc -l)
     if [ ! "$number_jobs" -eq 0 ]; then
         PS1+=$(section_end $fg_color $bg_color)
-        PS1+=$(section_content $fg_color $bg_color " ⏎$number_jobs ")
+        PS1+=$(section_content $fg_color $bg_color " ${symbols[enter]}$number_jobs ")
         __last_color=$bg_color
     fi
 }
@@ -107,7 +107,7 @@ function read_only_module {
     local fg_color=$2
     if [ ! -w "$PWD" ]; then
         PS1+=$(section_end $fg_color $bg_color)
-        PS1+=$(section_content $fg_color $bg_color "  ")
+        PS1+=$(section_content $fg_color $bg_color " ${symbols[lock]} ")
         __last_color=$bg_color
     fi
 }
@@ -120,21 +120,21 @@ function read_only_module {
 function git_module {
     local git_branch=$(git_branch_name)
     if [ ! -z "$git_branch" ]; then
-        local content=" $git_branch$git"
+        local content="${symbols[git]} $git_branch$git"
 
         local number_modified=$(git diff --name-only --diff-filter=M 2> /dev/null | wc -l )
         if [ ! "$number_modified" -eq "0" ]; then
-            content+="  ✚$number_modified"
+            content+=" ${symbols[soft_separator]} ${symbols[plus]}$number_modified"
         fi
 
         local number_staged=$(git diff --staged --name-only --diff-filter=AM 2> /dev/null | wc -l)
         if [ ! "$number_staged" -eq "0" ]; then
-            content+="  ✔$number_staged"
+            content+=" ${symbols[soft_separator]} ${symbols[tick]}$number_staged"
         fi
 
         local number_conflicts=$(git diff --name-only --diff-filter=U 2> /dev/null | wc -l)
         if [ ! "$number_conflicts" -eq "0" ]; then
-            content+="  ✘$number_conflicts"
+            content+=" ${symbols[soft_separator]} ${symbols[cross]}$number_conflicts"
         fi
 
         local bg_color=$1
@@ -154,7 +154,7 @@ function virtual_env_module {
         local venv="${VIRTUAL_ENV##*/}"
         local bg_color=$1
         local fg_color=$2
-        local content=" λ $venv "
+        local content=" ${symbols[python]} $venv "
         PS1+=$(section_end $fg_color $bg_color)
         PS1+=$(section_content $fg_color $bg_color "$content")
         __last_color=$bg_color
@@ -168,7 +168,7 @@ function prompt_module {
     if [ "$3" = true ] && [ ! "$return_code" -eq 0 ]; then
         local bg_color="Red"
         local fg_color="White"
-        local content=" $ ⚑ $return_code "
+        local content=" $ ${symbols[flag]} $return_code "
     else
         local bg_color=$1
         local fg_color=$2
@@ -181,32 +181,22 @@ function prompt_module {
 
 # -----------------------------------------------------------------------------
 function pureline_ps1 {
-    return_code=$? # save return code
+    return_code=$?      # save the return code
     PS1=""
 
-    # Source a config file or load the default modules
-    if [ -f "$__pureline_config" ]; then
-        source "$__pureline_config"
-    else
-        #   Module Name	    Background	Foreground	Optional Argument
-        time_module         "Purple"    "Black"
-        host_module         "Yellow"    "Black"		false # Show User
-        virtual_env_module  "Blue"      "Black"
-        path_module         "Blue"      "Black"
-        read_only_module    "Red"       "White"
-        jobs_module         "Purple"    "Black"
-        git_module          "Green"     "Black"
-        prompt_module       "Purple"    "Black"		true  # Return code
-    fi
+    # load the modules
+    for module in "${!pureline_modules[@]}"; do
+        ${pureline_modules[$module]}
+    done
 
-    # Final end point
+    # final end point
     if [ ! -z "$__last_color" ]; then
         PS1+=$(section_end)
     else
         PS1="$"
     fi
 
-    # Set the prompt and cleanup
+    # cleanup
     PS1+="${colors[Color_Off]} "
     unset __last_color
     unset return_code
@@ -215,34 +205,58 @@ function pureline_ps1 {
 # -----------------------------------------------------------------------------
 
 # define the basic color set
-
 declare -A colors
-colors[Color_Off]='\[\e[0m\]'       # Text Reset
+colors=(
+    [Color_Off]='\[\e[0m\]'       # Text Reset
+    # Foreground
+    [Black]='\[\e[0;30m\]'        # Black
+    [Red]='\[\e[0;31m\]'          # Red
+    [Green]='\[\e[0;32m\]'        # Green
+    [Yellow]='\[\e[0;33m\]'       # Yellow
+    [Blue]='\[\e[0;34m\]'         # Blue
+    [Purple]='\[\e[0;35m\]'       # Purple
+    [Cyan]='\[\e[0;36m\]'         # Cyan
+    [White]='\[\e[0;37m\]'        # White
+    # Background
+    [On_Black]='\[\e[40m\]'       # Black
+    [On_Red]='\[\e[41m\]'         # Red
+    [On_Green]='\[\e[42m\]'       # Green
+    [On_Yellow]='\[\e[43m\]'      # Yellow
+    [On_Blue]='\[\e[44m\]'        # Blue
+    [On_Purple]='\[\e[45m\]'      # Purple
+    [On_Cyan]='\[\e[46m\]'        # Cyan
+    [On_White]='\[\e[47m\]'       # White
+)
 
-# Foreground
-colors[Black]='\[\e[0;30m\]'        # Black
-colors[Red]='\[\e[0;31m\]'          # Red
-colors[Green]='\[\e[0;32m\]'        # Green
-colors[Yellow]='\[\e[0;33m\]'       # Yellow
-colors[Blue]='\[\e[0;34m\]'         # Blue
-colors[Purple]='\[\e[0;35m\]'       # Purple
-colors[Cyan]='\[\e[0;36m\]'         # Cyan
-colors[White]='\[\e[0;37m\]'        # White
+# define symbols
+declare -A symbols
+symbols=(
+    [hard_separator]=""
+    [soft_separator]=""
+    [git]=""
+    [folder]=" "
+    [lock]=""
+    [host]=" "
+    [flag]="⚑"
+    [plus]="✚"
+    [tick]="✔"
+    [cross]="✘"
+    [enter]="⏎"
+    [python]="λ"
+)
 
-# Background
-colors[On_Black]='\[\e[40m\]'       # Black
-colors[On_Red]='\[\e[41m\]'         # Red
-colors[On_Green]='\[\e[42m\]'       # Green
-colors[On_Yellow]='\[\e[43m\]'      # Yellow
-colors[On_Blue]='\[\e[44m\]'        # Blue
-colors[On_Purple]='\[\e[45m\]'      # Purple
-colors[On_Cyan]='\[\e[46m\]'        # Cyan
-colors[On_White]='\[\e[47m\]'       # White
-
-# Check if an argument has been given for the config
+# check if an argument has been given for a config file
 if [ -f "$1" ]; then
-    __pureline_config=$1
+    source $1
+else
+    # define default modules to load
+    declare -a pureline_modules=(
+        'host_module         Yellow    Black		false'
+        'path_module         Blue      Black'
+        'read_only_module    Red       White'
+    )
 fi
 
-# Dynamically set the  PS1
+# dynamically set the  PS1
 PROMPT_COMMAND=pureline_ps1
+
