various tweaks, no major changes

diff --git a/pureline b/pureline
--- a/pureline
+++ b/pureline
@@ -56,30 +56,24 @@ function segment_content {
 #------------------------------------------------------------------------------
 # Helper function for User segment - also used in external ssh segment
 function ip_address {
-    local ip_address
+    local address
     local ip_loc
     local ifconfig_loc
 
     # check if the ip command exists
     if ip_loc="$(type -p "ip")" || [[ -n $ip_loc ]]; then
         # shellcheck disable=SC2005
-        ip_address="$(ip route get 1 | tr -s ' ' | cut -d' ' -f7)"
+        address="$(ip route get 1 | tr -s ' ' | cut -d' ' -f7)"
     elif ifconfig_loc="$(type -p "ifconfig")" || [[ -n $ifconfig_loc ]]; then
         while IFS=$': \t' read -ra _line ;do
             [ -z "${_line%inet}"   ] &&
                 _ip=${_line[${#_line[1]}>4?1:2]} &&
-                [ "${_ip#127.0.0.1}"   ] && ip_address=$_ip
+                [ "${_ip#127.0.0.1}"   ] && address=$_ip
         done< <(LANG=C /sbin/ifconfig)
     else
-        ip_address="127.0.0.1"
+        address="127.0.0.1"
     fi
-    echo "$ip_address"
-}
-
-#------------------------------------------------------------------------------
-# Helper function to return normal or super user prompt character
-function prompt_char {
-    [[ ${EUID} -eq 0 ]] && echo "#" || echo "$"
+    echo "$address"
 }
 
 # -----------------------------------------------------------------------------
@@ -139,7 +133,7 @@ function path_segment {
     local fg_color="$2"
     local content="\w"
     if [[ $PL_PATH_TRIM -eq 1 ]]; then
-        local content="\W"
+        content="\W"
     elif [[ $PL_PATH_TRIM -gt 1 ]]; then
         PROMPT_DIRTRIM="$PL_PATH_TRIM"
     fi
@@ -186,7 +180,6 @@ function prompt_segment {
     local bg_color="$1"
     local fg_color="$2"
     local content
-    content=" $(prompt_char) "
     if [[ ${EUID} -eq 0 ]]; then
         if [[ -n $PL_PROMPT_ROOT_FG ]]; then
             fg_color="$PL_PROMPT_ROOT_FG"
@@ -196,7 +189,7 @@ function prompt_segment {
         fi
     fi
     PS1+="$(segment_end "$fg_color" "$bg_color")"
-    PS1+="$(segment_content "$fg_color" "$bg_color" "$content")"
+    PS1+="$(segment_content "$fg_color" "$bg_color" " $PL_PROMPT_CHAR ")"
     __last_color="$bg_color"
 }
 
@@ -229,16 +222,16 @@ function newline_segment {
 # -----------------------------------------------------------------------------
 # code to run before processing $PROMT_COMMAND
 function pureline_pre {
-    __return_code=$?                    # save return code of last command
-    echo -ne "\e]2;${PL_TITLEBAR@P}\a"  # set the gui window title
+    __return_code=$? # save return code of last command
+    [[ $PL_SET_TITLEBAR == true ]] && echo -ne "\e]2;${PL_TITLEBAR@P}\a"  # set the gui window title
 }
 
 # -----------------------------------------------------------------------------
 function pureline_ps1 {
-    local segment_index
     PS1=""                                  # reset the command prompt
 
     # load the segments
+    local segment_index
     for segment_index in "${!PL_SEGMENTS[@]}"; do
         ${PL_SEGMENTS[$segment_index]};
     done
@@ -248,7 +241,7 @@ function pureline_ps1 {
         PS1+="$(segment_end "$__last_color" 'Default') "
     else
         # No segments loaded, set a basic prompt
-        PS1="No PureLine Segments: $(prompt_char)"
+        PS1="No PureLine Segments: $PL_PROMPT_CHAR"
     fi
 
     # cleanup
@@ -342,8 +335,10 @@ function main() {
     set_default_segments
 
     # set some defaults
+    PL_SET_TITLEBAR=false
     PL_TITLEBAR="\u@\h: \w" # title bar setting can use PS1 style \u etc
     PL_ERASE_TO_EOL=false   # need on some terminals to prevent glitches
+    [[ ${EUID} -eq 0 ]] && PL_PROMPT_CHAR='#' || PL_PROMPT_CHAR='$'
 
     # check if an argument has been given for a config file
     if [[ -f $1 ]]; then
