bugfix

diff --git a/pureline b/pureline
--- a/pureline
+++ b/pureline
@@ -7,18 +7,18 @@
 # arg: $1 is foreground color of the next section
 # arg: $2 is background color of the next section
 function section_end {
-	if [ "$__last_color" == "$2" ]; then
-		# Section colors are the same, use a foreground separator
-		local end_char="${symbols[soft_separator]}"
-		local fg=$1
-	else
-		# section colors are different, use a background separator
-		local end_char="${symbols[hard_separator]}"
-		local fg=$__last_color
-	fi
-	if [ -n "$__last_color" ]; then
-		echo "${PL_COLORS[$fg]}${PL_COLORS[On_$2]}$end_char"
-	fi
+    if [ "$__last_color" == "$2" ]; then
+        # Section colors are the same, use a foreground separator
+        local end_char="${symbols[soft_separator]}"
+        local fg=$1
+    else
+        # section colors are different, use a background separator
+        local end_char="${symbols[hard_separator]}"
+        local fg=$__last_color
+    fi
+    if [ -n "$__last_color" ]; then
+        echo "${PL_COLORS[$fg]}${PL_COLORS[On_$2]}$end_char"
+    fi
 }
 
 # -----------------------------------------------------------------------------
@@ -27,7 +27,7 @@ function section_end {
 # arg: $2 background color
 # arg: $3 content
 function section_content {
-	echo "${PL_COLORS[$1]}${PL_COLORS[On_$2]}$3"
+    echo "${PL_COLORS[$1]}${PL_COLORS[On_$2]}$3"
 }
 
 # -----------------------------------------------------------------------------
@@ -36,16 +36,16 @@ function section_content {
 # arg: $2 background color
 # optional arg: $3 - true/false to show seconds
 function time_module {
-	local bg_color=$1
-	local fg_color=$2
-	if [ "$PL_TIME_SHOW_SECONDS" = true ]; then
-		local content="\t"
-	else
-		local content="\A"
-	fi
-	PS1+=$(section_end $fg_color $bg_color)
-	PS1+=$(section_content $fg_color $bg_color " $content ")
-	__last_color=$bg_color
+    local bg_color=$1
+    local fg_color=$2
+    if [ "$PL_TIME_SHOW_SECONDS" = true ]; then
+        local content="\t"
+    else
+        local content="\A"
+    fi
+    PS1+=$(section_end $fg_color $bg_color)
+    PS1+=$(section_content $fg_color $bg_color " $content ")
+    __last_color=$bg_color
 }
 
 #------------------------------------------------------------------------------
@@ -60,20 +60,20 @@ function ip_address {
 # arg: $2 background color
 # optional arg: $3 - true/false to show the hostname
 function user_module {
-	local bg_color=$1
-	local fg_color=$2
-	local content="\u"
-	# Show host if true or when user is remote/root
-	if [ "$PL_USER_SHOW_HOST" = true ]; then
-	    if [ "$PL_USER_USE_IP" = true ]; then
+    local bg_color=$1
+    local fg_color=$2
+    local content="\u"
+    # Show host if true or when user is remote/root
+    if [ "$PL_USER_SHOW_HOST" = true ]; then
+        if [ "$PL_USER_USE_IP" = true ]; then
             content+="@$(ip_address)"
         else
-		    content+="@\h"
-		fi
-	fi
-	PS1+=$(section_end $fg_color $bg_color)
-	PS1+=$(section_content $fg_color $bg_color " $content ")
-	__last_color=$bg_color
+            content+="@\h"
+        fi
+    fi
+    PS1+=$(section_end $fg_color $bg_color)
+    PS1+=$(section_content $fg_color $bg_color " $content ")
+    __last_color=$bg_color
 }
 
 # -----------------------------------------------------------------------------
@@ -82,7 +82,7 @@ function user_module {
 # arg: $2 background color
 # optional arg: $3 - true/false to show the hostname
 function ssh_module {
-	if [[ "${SSH_CLIENT}" || "${SSH_TTY}" ]]; then
+    if [[ "${SSH_CLIENT}" || "${SSH_TTY}" ]]; then
         local bg_color=$1
         local fg_color=$2
         local content="${symbols[ssh]}"
@@ -106,17 +106,17 @@ function ssh_module {
 # option variables:
 # $PL_PATH_TRIM; 0—fullpath, 1—current dir, [x]—trim to x number of dir
 function path_module {
-	local bg_color=$1
-	local fg_color=$2
-	local content="\w"
-	if [ "$PL_PATH_TRIM" -eq 1 ]; then
-		local content="\W"
-	elif [ "$PL_PATH_TRIM" -gt 1 ]; then
+    local bg_color=$1
+    local fg_color=$2
+    local content="\w"
+    if [ "$PL_PATH_TRIM" -eq 1 ]; then
+        local content="\W"
+    elif [ "$PL_PATH_TRIM" -gt 1 ]; then
         PROMPT_DIRTRIM=$PL_PATH_TRIM
-	fi
-	PS1+=$(section_end $fg_color $bg_color)
-	PS1+=$(section_content $fg_color $bg_color " $content ")
-	__last_color=$bg_color
+    fi
+    PS1+=$(section_end $fg_color $bg_color)
+    PS1+=$(section_content $fg_color $bg_color " $content ")
+    __last_color=$bg_color
 }
 
 # -----------------------------------------------------------------------------
@@ -124,14 +124,14 @@ function path_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function background_jobs_module {
-	local bg_color=$1
-	local fg_color=$2
-	local number_jobs=$(jobs -p | wc -l)
-	if [ ! "$number_jobs" -eq 0 ]; then
-		PS1+=$(section_end $fg_color $bg_color)
-		PS1+=$(section_content $fg_color $bg_color " ${symbols[background_jobs]} $number_jobs ")
-		__last_color=$bg_color
-	fi
+    local bg_color=$1
+    local fg_color=$2
+    local number_jobs=$(jobs -p | wc -l)
+    if [ ! "$number_jobs" -eq 0 ]; then
+        PS1+=$(section_end $fg_color $bg_color)
+        PS1+=$(section_content $fg_color $bg_color " ${symbols[background_jobs]} $number_jobs ")
+        __last_color=$bg_color
+    fi
 }
 
 # -----------------------------------------------------------------------------
@@ -139,13 +139,13 @@ function background_jobs_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function read_only_module {
-	local bg_color=$1
-	local fg_color=$2
-	if [ ! -w "$PWD" ]; then
-		PS1+=$(section_end $fg_color $bg_color)
-		PS1+=$(section_content $fg_color $bg_color " ${symbols[read_only]} ")
-		__last_color=$bg_color
-	fi
+    local bg_color=$1
+    local fg_color=$2
+    if [ ! -w "$PWD" ]; then
+        PS1+=$(section_end $fg_color $bg_color)
+        PS1+=$(section_content $fg_color $bg_color " ${symbols[read_only]} ")
+        __last_color=$bg_color
+    fi
 }
 
 # -----------------------------------------------------------------------------
@@ -156,11 +156,11 @@ function read_only_module {
 # optional arg: $3 - foreground color used if the working directory is dirty
 # optional arg: $4 - show ahead/behind status
 function git_module {
-	local git_branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
-	if [ -n "$git_branch" ]; then
-		local bg_color=$1
-		local fg_color=$2
-		local content="${symbols[git_branch]} $git_branch"
+    local git_branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
+    if [ -n "$git_branch" ]; then
+        local bg_color=$1
+        local fg_color=$2
+        local content="${symbols[git_branch]} $git_branch"
 
         if [ "$PL_GIT_STASH" = true ]; then
             local number_stash=$(git stash list 2>/dev/null | wc -l)
@@ -183,47 +183,49 @@ function git_module {
             fi
         fi
 
-		if [ "$PL_GIT_STAGED" = true ]; then
+        if [ "$PL_GIT_STAGED" = true ]; then
             local number_staged=$(git diff --staged --name-only --diff-filter=AM 2> /dev/null | wc -l)
             if [ ! "$number_staged" -eq "0" ]; then
                 content+=" ${symbols[soft_separator]} ${symbols[git_staged]}$number_staged"
             fi
         fi
 
-		if [ "$PL_GIT_CONFLICTS" = true ]; then
+        if [ "$PL_GIT_CONFLICTS" = true ]; then
             local number_conflicts=$(git diff --name-only --diff-filter=U 2> /dev/null | wc -l)
             if [ ! "$number_conflicts" -eq "0" ]; then
                 content+=" ${symbols[soft_separator]} ${symbols[git_conflicts]}$number_conflicts"
             fi
         fi
 
-		if [ "$PL_GIT_MODIFIED" = true ]; then
+        if [ "$PL_GIT_MODIFIED" = true ]; then
             local number_modified=$(git diff --name-only --diff-filter=M 2> /dev/null | wc -l )
             if [ ! "$number_modified" -eq "0" ]; then
                 content+=" ${symbols[soft_separator]} ${symbols[git_modified]}$number_modified"
             fi
         fi
 
-		if [ "$PL_GIT_UNTRACKED" = true ]; then
+        if [ "$PL_GIT_UNTRACKED" = true ]; then
             local number_untracked=$(git ls-files --other --exclude-standard | wc -l)
             if [ ! "$number_untracked" -eq "0" ]; then
                 content+=" ${symbols[soft_separator]} ${symbols[git_untracked]}$number_untracked"
             fi
         fi
 
-		if [[ -n "$PL_GIT_DIRTY_FG" || -n "$PL_GIT_DIRTY_BG" && -n "$(git status --porcelain)" ]]; then
-		    if [ -n "$PL_GIT_DIRTY_FG" ]; then
-		        fg_color=$PL_GIT_DIRTY_FG
-		    fi
-		    if [ -n "$PL_GIT_DIRTY_BG" ]; then
-		        bg_color=$PL_GIT_DIRTY_BG
-		    fi
-		fi
+        if [[ -n "$PL_GIT_DIRTY_FG" || -n "$PL_GIT_DIRTY_BG" ]]; then
+            if [ -n "$(git status --porcelain)" ]; then
+                if [ -n "$PL_GIT_DIRTY_FG" ]; then
+                    fg_color=$PL_GIT_DIRTY_FG
+                fi
+                if [ -n "$PL_GIT_DIRTY_BG" ]; then
+                    bg_color=$PL_GIT_DIRTY_BG
+                fi
+            fi
+        fi
 
-		PS1+=$(section_end $fg_color $bg_color)
-		PS1+=$(section_content $fg_color $bg_color " $content ")
-		__last_color=$bg_color
-	fi
+        PS1+=$(section_end $fg_color $bg_color)
+        PS1+=$(section_content $fg_color $bg_color " $content ")
+        __last_color=$bg_color
+    fi
 }
 
 # -----------------------------------------------------------------------------
@@ -231,15 +233,15 @@ function git_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function virtual_env_module {
-	if [ -n "$VIRTUAL_ENV" ]; then
-		local venv="${VIRTUAL_ENV##*/}"
-		local bg_color=$1
-		local fg_color=$2
-		local content=" ${symbols[python]} $venv"
-		PS1+=$(section_end $fg_color $bg_color)
-		PS1+=$(section_content $fg_color $bg_color "$content ")
-		__last_color=$bg_color
-	fi
+    if [ -n "$VIRTUAL_ENV" ]; then
+        local venv="${VIRTUAL_ENV##*/}"
+        local bg_color=$1
+        local fg_color=$2
+        local content=" ${symbols[python]} $venv"
+        PS1+=$(section_end $fg_color $bg_color)
+        PS1+=$(section_content $fg_color $bg_color "$content ")
+        __last_color=$bg_color
+    fi
 }
 
 # -----------------------------------------------------------------------------
@@ -247,31 +249,31 @@ function virtual_env_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function battery_module {
-	local bg_color=$1
-	local fg_color=$2
-	local batt_dir
-	local content
-	local batt_dir="/sys/class/power_supply/BAT"
-	if [ -d $batt_dir"0" ]; then
-		batt_dir=$batt_dir"0"
-	elif [ -d $batt_dir"1" ]; then
-		batt_dir=$batt_dir1""
-	else
-		return 1
-	fi
-	local cap=$(<"$batt_dir/capacity")
-	local status=$(<"$batt_dir/status")
+    local bg_color=$1
+    local fg_color=$2
+    local batt_dir
+    local content
+    local batt_dir="/sys/class/power_supply/BAT"
+    if [ -d $batt_dir"0" ]; then
+        batt_dir=$batt_dir"0"
+    elif [ -d $batt_dir"1" ]; then
+        batt_dir=$batt_dir1""
+    else
+        return 1
+    fi
+    local cap=$(<"$batt_dir/capacity")
+    local status=$(<"$batt_dir/status")
 
-	if [ "$status" == "Discharging" ]; then
-		content="${symbols[battery_discharging]} "
-	else
-		content="${symbols[battery_charging]}"
-	fi
-	content="$content$cap%"
+    if [ "$status" == "Discharging" ]; then
+        content="${symbols[battery_discharging]} "
+    else
+        content="${symbols[battery_charging]}"
+    fi
+    content="$content$cap%"
 
-	PS1+=$(section_end $fg_color $bg_color)
-	PS1+=$(section_content $fg_color $bg_color " $content ")
-	__last_color=$bg_color
+    PS1+=$(section_end $fg_color $bg_color)
+    PS1+=$(section_content $fg_color $bg_color " $content ")
+    __last_color=$bg_color
 }
 
 
@@ -280,18 +282,18 @@ function battery_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function prompt_module {
-	# if we're root then use '#' as the prompt-string
-	if [ ${EUID} -eq 0 ]; then
-		local prompt_char="#"
-	else
-		local prompt_char="$"
-	fi
-	local bg_color=$1
-	local fg_color=$2
-	local content=" $prompt_char "
-	PS1+=$(section_end $fg_color $bg_color)
-	PS1+=$(section_content $fg_color $bg_color "$content")
-	__last_color=$bg_color
+    # if we're root then use '#' as the prompt-string
+    if [ ${EUID} -eq 0 ]; then
+        local prompt_char="#"
+    else
+        local prompt_char="$"
+    fi
+    local bg_color=$1
+    local fg_color=$2
+    local content=" $prompt_char "
+    PS1+=$(section_end $fg_color $bg_color)
+    PS1+=$(section_content $fg_color $bg_color "$content")
+    __last_color=$bg_color
 }
 
 # -----------------------------------------------------------------------------
@@ -299,47 +301,47 @@ function prompt_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function return_code_module {
-	if [ ! "$__return_code" -eq 0 ]; then
-		local bg_color=$1
-		local fg_color=$2
-		local content=" ${symbols[return_code]} $__return_code "
-		PS1+=$(section_end $fg_color $bg_color)
-		PS1+=$(section_content $fg_color $bg_color "$content")
-		__last_color=$bg_color
-	fi
+    if [ ! "$__return_code" -eq 0 ]; then
+        local bg_color=$1
+        local fg_color=$2
+        local content=" ${symbols[return_code]} $__return_code "
+        PS1+=$(section_end $fg_color $bg_color)
+        PS1+=$(section_content $fg_color $bg_color "$content")
+        __last_color=$bg_color
+    fi
 }
 
 # -----------------------------------------------------------------------------
 # append to prompt: end the current promptline and start a newline
 function newline_module {
-	if [ -n "$__last_color" ]; then
-		PS1+=$(section_end $__last_color 'Default')
-	fi
-	PS1+="\n"
-	unset __last_color
+    if [ -n "$__last_color" ]; then
+        PS1+=$(section_end $__last_color 'Default')
+    fi
+    PS1+="\n"
+    unset __last_color
 }
 
 # -----------------------------------------------------------------------------
 function pureline_ps1 {
-	__return_code=$?      # save the return code
-	PS1=""
+    __return_code=$?      # save the return code
+    PS1=""
 
-	# load the modules
-	for module in "${!PL_MODULES[@]}"; do
-		${PL_MODULES[$module]}
-	done
+    # load the modules
+    for module in "${!PL_MODULES[@]}"; do
+        ${PL_MODULES[$module]}
+    done
 
-	# final end point
-	if [ -n "$__last_color" ]; then
-		PS1+=$(section_end $__last_color 'Default')
-	else
-		PS1="$"
-	fi
+    # final end point
+    if [ -n "$__last_color" ]; then
+        PS1+=$(section_end $__last_color 'Default')
+    else
+        PS1="$"
+    fi
 
-	# cleanup
-	PS1+="${PL_COLORS[Color_Off]}\[\e[K\] "
-	unset __last_color
-	unset __return_code
+    # cleanup
+    PS1+="${PL_COLORS[Color_Off]}\[\e[K\] "
+    unset __last_color
+    unset __return_code
 }
 
 # -----------------------------------------------------------------------------
@@ -394,16 +396,16 @@ declare -A symbols=(
 
 # check if an argument has been given for a config file
 if [ -f "$1" ]; then
-	source $1
+    source $1
 else
-	# define default modules to load
-	declare -a PL_MODULES=(
-	'user_module        Yellow      Black'
-	'path_module        Blue        Black'
-	'read_only_module   Red         White'
-	)
-	PL_USER_SHOW_HOST=true
-	PL_PATH_TRIM=1
+    # define default modules to load
+    declare -a PL_MODULES=(
+    'user_module        Yellow      Black'
+    'path_module        Blue        Black'
+    'read_only_module   Red         White'
+    )
+    PL_USER_SHOW_HOST=true
+    PL_PATH_TRIM=1
 fi
 
 # dynamically set the  PS1
