Quoted all variable assignments to improve performance by avoiding unnecessary globbing analysis

diff --git a/pureline b/pureline
--- a/pureline
+++ b/pureline
@@ -10,11 +10,11 @@ function section_end {
     if [ "$__last_color" == "$2" ]; then
         # Section colors are the same, use a foreground separator
         local end_char="${PL_SYMBOLS[soft_separator]}"
-        local fg=$1
+        local fg="$1"
     else
         # section colors are different, use a background separator
         local end_char="${PL_SYMBOLS[hard_separator]}"
-        local fg=$__last_color
+        local fg="$__last_color"
     fi
     if [ -n "$__last_color" ]; then
         echo "${PL_COLORS[$fg]}${PL_COLORS[On_$2]}$end_char"
@@ -46,18 +46,19 @@ function prompt_char {
 # append to prompt: current time
 # arg: $1 foreground color
 # arg: $2 background color
-# optional arg: $3 - true/false to show seconds
+# optional variables;
+#   PL_TIME_SHOW_SECONDS: true/false for hh:mm:ss / hh:mm
 function time_module {
-    local bg_color=$1
-    local fg_color=$2
+    local bg_color="$1"
+    local fg_color="$2"
     if [ "$PL_TIME_SHOW_SECONDS" = true ]; then
         local content="\t"
     else
         local content="\A"
     fi
-    PS1+=$(section_end $fg_color $bg_color)
-    PS1+=$(section_content $fg_color $bg_color " $content ")
-    __last_color=$bg_color
+    PS1+="$(section_end $fg_color $bg_color)"
+    PS1+="$(section_content $fg_color $bg_color " $content ")"
+    __last_color="$bg_color"
 }
 
 #------------------------------------------------------------------------------
@@ -68,8 +69,8 @@ function time_module {
 #   PL_USER_SHOW_HOST: true/false to show host name/ip
 #   PL_USER_USE_IP: true/false to show IP instead of hostname
 function user_module {
-    local bg_color=$1
-    local fg_color=$2
+    local bg_color="$1"
+    local fg_color="$2"
     local content="\u"
     # Show host if true or when user is remote/root
     if [ "$PL_USER_SHOW_HOST" = true ]; then
@@ -79,9 +80,9 @@ function user_module {
             content+="@\h"
         fi
     fi
-    PS1+=$(section_end $fg_color $bg_color)
-    PS1+=$(section_content $fg_color $bg_color " $content ")
-    __last_color=$bg_color
+    PS1+="$(section_end $fg_color $bg_color)"
+    PS1+="$(section_content $fg_color $bg_color " $content ")"
+    __last_color="$bg_color"
 }
 
 # -----------------------------------------------------------------------------
@@ -93,8 +94,8 @@ function user_module {
 #   PL_SSH_USE_IP: true/false to show IP instead of hostname
 function ssh_module {
     if [[ "${SSH_CLIENT}" || "${SSH_TTY}" ]]; then
-        local bg_color=$1
-        local fg_color=$2
+        local bg_color="$1"
+        local fg_color="$2"
         local content="${PL_SYMBOLS[ssh]}"
         if [ "$PL_SSH_SHOW_HOST" = true ]; then
             if [ "$PL_SSH_USE_IP" = true ]; then
@@ -103,9 +104,9 @@ function ssh_module {
                 content+=" \h"
             fi
         fi
-        PS1+=$(section_end $fg_color $bg_color)
-        PS1+=$(section_content $fg_color $bg_color " $content ")
-        __last_color=$bg_color
+        PS1+="$(section_end $fg_color $bg_color)"
+        PS1+="$(section_content $fg_color $bg_color " $content ")"
+        __last_color="$bg_color"
     fi
 }
 
@@ -116,17 +117,17 @@ function ssh_module {
 # option variables;
 #   PL_PATH_TRIM: 0—fullpath, 1—current dir, [x]—trim to x number of dir
 function path_module {
-    local bg_color=$1
-    local fg_color=$2
+    local bg_color="$1"
+    local fg_color="$2"
     local content="\w"
     if [ "$PL_PATH_TRIM" -eq 1 ]; then
         local content="\W"
     elif [ "$PL_PATH_TRIM" -gt 1 ]; then
-        PROMPT_DIRTRIM=$PL_PATH_TRIM
+        PROMPT_DIRTRIM="$PL_PATH_TRIM"
     fi
-    PS1+=$(section_end $fg_color $bg_color)
-    PS1+=$(section_content $fg_color $bg_color " $content ")
-    __last_color=$bg_color
+    PS1+="$(section_end $fg_color $bg_color)"
+    PS1+="$(section_content $fg_color $bg_color " $content ")"
+    __last_color="$bg_color"
 }
 
 # -----------------------------------------------------------------------------
@@ -134,13 +135,13 @@ function path_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function background_jobs_module {
-    local bg_color=$1
-    local fg_color=$2
+    local bg_color="$1"
+    local fg_color="$2"
     local number_jobs=$(jobs -p | wc -l)
     if [ ! "$number_jobs" -eq 0 ]; then
-        PS1+=$(section_end $fg_color $bg_color)
-        PS1+=$(section_content $fg_color $bg_color " ${PL_SYMBOLS[background_jobs]} $number_jobs ")
-        __last_color=$bg_color
+        PS1+="$(section_end $fg_color $bg_color)"
+        PS1+="$(section_content $fg_color $bg_color " ${PL_SYMBOLS[background_jobs]} $number_jobs ")"
+        __last_color="$bg_color"
     fi
 }
 
@@ -149,12 +150,12 @@ function background_jobs_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function read_only_module {
-    local bg_color=$1
-    local fg_color=$2
+    local bg_color="$1"
+    local fg_color="$2"
     if [ ! -w "$PWD" ]; then
-        PS1+=$(section_end $fg_color $bg_color)
-        PS1+=$(section_content $fg_color $bg_color " ${PL_SYMBOLS[read_only]} ")
-        __last_color=$bg_color
+        PS1+="$(section_end $fg_color $bg_color)"
+        PS1+="$(section_content $fg_color $bg_color " ${PL_SYMBOLS[read_only]} ")"
+        __last_color="$bg_color"
     fi
 }
 
@@ -173,19 +174,19 @@ function read_only_module {
 function git_module {
     local git_branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
     if [ -n "$git_branch" ]; then
-        local bg_color=$1
-        local fg_color=$2
+        local bg_color="$1"
+        local fg_color="$2"
         local content="${PL_SYMBOLS[git_branch]} $git_branch"
 
         if [ "$PL_GIT_STASH" = true ]; then
-            local number_stash=$(git stash list 2>/dev/null | wc -l)
+            local number_stash="$(git stash list 2>/dev/null | wc -l)"
             if [ ! "$number_stash" -eq 0 ]; then
                 content+="${PL_SYMBOLS[git_stash]}$number_stash"
             fi
         fi
 
         if [ "$PL_GIT_AHEAD" = true ]; then
-            local number_behind_ahead=$(git rev-list --count --left-right '@{upstream}...HEAD' 2>/dev/null)
+            local number_behind_ahead="$(git rev-list --count --left-right '@{upstream}...HEAD' 2>/dev/null)"
             local number_ahead="${number_behind_ahead#*	}"
             local number_behind="${number_behind_ahead%	*}"
             if [ ! "0$number_ahead" -eq 0 -o ! "0$number_behind" -eq 0 ]; then
@@ -199,28 +200,28 @@ function git_module {
         fi
 
         if [ "$PL_GIT_STAGED" = true ]; then
-            local number_staged=$(git diff --staged --name-only --diff-filter=AM 2> /dev/null | wc -l)
+            local number_staged="$(git diff --staged --name-only --diff-filter=AM 2> /dev/null | wc -l)"
             if [ ! "$number_staged" -eq "0" ]; then
                 content+=" ${PL_SYMBOLS[soft_separator]} ${PL_SYMBOLS[git_staged]}$number_staged"
             fi
         fi
 
         if [ "$PL_GIT_CONFLICTS" = true ]; then
-            local number_conflicts=$(git diff --name-only --diff-filter=U 2> /dev/null | wc -l)
+            local number_conflicts="$(git diff --name-only --diff-filter=U 2> /dev/null | wc -l)"
             if [ ! "$number_conflicts" -eq "0" ]; then
                 content+=" ${PL_SYMBOLS[soft_separator]} ${PL_SYMBOLS[git_conflicts]}$number_conflicts"
             fi
         fi
 
         if [ "$PL_GIT_MODIFIED" = true ]; then
-            local number_modified=$(git diff --name-only --diff-filter=M 2> /dev/null | wc -l )
+            local number_modified="$(git diff --name-only --diff-filter=M 2> /dev/null | wc -l )"
             if [ ! "$number_modified" -eq "0" ]; then
                 content+=" ${PL_SYMBOLS[soft_separator]} ${PL_SYMBOLS[git_modified]}$number_modified"
             fi
         fi
 
         if [ "$PL_GIT_UNTRACKED" = true ]; then
-            local number_untracked=$(git ls-files --other --exclude-standard | wc -l)
+            local number_untracked="$(git ls-files --other --exclude-standard | wc -l)"
             if [ ! "$number_untracked" -eq "0" ]; then
                 content+=" ${PL_SYMBOLS[soft_separator]} ${PL_SYMBOLS[git_untracked]}$number_untracked"
             fi
@@ -228,16 +229,16 @@ function git_module {
 
         if [ -n "$(git status --porcelain)" ]; then
             if [ -n "$PL_GIT_DIRTY_FG" ]; then
-                fg_color=$PL_GIT_DIRTY_FG
+                fg_color="$PL_GIT_DIRTY_FG"
             fi
             if [ -n "$PL_GIT_DIRTY_BG" ]; then
-                bg_color=$PL_GIT_DIRTY_BG
+                bg_color="$PL_GIT_DIRTY_BG"
             fi
         fi
 
-        PS1+=$(section_end $fg_color $bg_color)
-        PS1+=$(section_content $fg_color $bg_color " $content ")
-        __last_color=$bg_color
+        PS1+="$(section_end $fg_color $bg_color)"
+        PS1+="$(section_content $fg_color $bg_color " $content ")"
+        __last_color="$bg_color"
     fi
 }
 
@@ -248,12 +249,12 @@ function git_module {
 function virtual_env_module {
     if [ -n "$VIRTUAL_ENV" ]; then
         local venv="${VIRTUAL_ENV##*/}"
-        local bg_color=$1
-        local fg_color=$2
+        local bg_color="$1"
+        local fg_color="$2"
         local content=" ${PL_SYMBOLS[python]} $venv"
-        PS1+=$(section_end $fg_color $bg_color)
-        PS1+=$(section_content $fg_color $bg_color "$content ")
-        __last_color=$bg_color
+        PS1+="$(section_end $fg_color $bg_color)"
+        PS1+="$(section_content $fg_color $bg_color "$content ")"
+        __last_color="$bg_color"
     fi
 }
 
@@ -262,8 +263,8 @@ function virtual_env_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function battery_module {
-    local bg_color=$1
-    local fg_color=$2
+    local bg_color="$1"
+    local fg_color="$2"
     local batt_dir
     local content
     local batt_dir="/sys/class/power_supply/BAT"
@@ -274,8 +275,8 @@ function battery_module {
     else
         return 1
     fi
-    local cap=$(<"$batt_dir/capacity")
-    local status=$(<"$batt_dir/status")
+    local cap="$(<"$batt_dir/capacity")"
+    local status="$(<"$batt_dir/status")"
 
     if [ "$status" == "Discharging" ]; then
         content="${PL_SYMBOLS[battery_discharging]} "
@@ -284,9 +285,9 @@ function battery_module {
     fi
     content="$content$cap%"
 
-    PS1+=$(section_end $fg_color $bg_color)
-    PS1+=$(section_content $fg_color $bg_color " $content ")
-    __last_color=$bg_color
+    PS1+="$(section_end $fg_color $bg_color)"
+    PS1+="$(section_content $fg_color $bg_color " $content ")"
+    __last_color="$bg_color"
 }
 
 # -----------------------------------------------------------------------------
@@ -294,12 +295,12 @@ function battery_module {
 # arg: $1 foreground color
 # arg; $2 background color
 function prompt_module {
-    local bg_color=$1
-    local fg_color=$2
+    local bg_color="$1"
+    local fg_color="$2"
     local content=" $(prompt_char) "
-    PS1+=$(section_end $fg_color $bg_color)
-    PS1+=$(section_content $fg_color $bg_color "$content")
-    __last_color=$bg_color
+    PS1+="$(section_end $fg_color $bg_color)"
+    PS1+="$(section_content $fg_color $bg_color "$content")"
+    __last_color="$bg_color"
 }
 
 # -----------------------------------------------------------------------------
@@ -308,12 +309,12 @@ function prompt_module {
 # arg; $2 background color
 function return_code_module {
     if [ ! "$__return_code" -eq 0 ]; then
-        local bg_color=$1
-        local fg_color=$2
+        local bg_color="$1"
+        local fg_color="$2"
         local content=" ${PL_SYMBOLS[return_code]} $__return_code "
-        PS1+=$(section_end $fg_color $bg_color)
-        PS1+=$(section_content $fg_color $bg_color "$content")
-        __last_color=$bg_color
+        PS1+="$(section_end $fg_color $bg_color)"
+        PS1+="$(section_content $fg_color $bg_color "$content")"
+        __last_color="$bg_color"
     fi
 }
 
@@ -321,7 +322,7 @@ function return_code_module {
 # append to prompt: end the current promptline and start a newline
 function newline_module {
     if [ -n "$__last_color" ]; then
-        PS1+=$(section_end $__last_color 'Default')
+        PS1+="$(section_end $__last_color 'Default')"
     fi
     PS1+="\n"
     unset __last_color
@@ -329,8 +330,8 @@ function newline_module {
 
 # -----------------------------------------------------------------------------
 function pureline_ps1 {
-    __return_code=$?      # save the return code
-    PS1=""
+    __return_code=$?    # save the return code
+    PS1=""              # reset the command prompt
 
     # load the modules
     for module in "${!PL_MODULES[@]}"; do
@@ -339,10 +340,10 @@ function pureline_ps1 {
 
     # final end point
     if [ -n "$__last_color" ]; then
-        PS1+=$(section_end $__last_color 'Default')
+        PS1+="$(section_end $__last_color 'Default')"
     else
         # No modules loaded, set a basic prompt
-        PS1=$(prompt_char)
+        PS1="$(prompt_char)"
     fi
 
     # cleanup
@@ -421,7 +422,7 @@ fi
 # appended to pureline when sourced without continually appending
 # pureline to itself.
 if [ -z "$__PROMPT_COMMAND" ]; then 
-    __PROMPT_COMMAND=$PROMPT_COMMAND
+    __PROMPT_COMMAND="$PROMPT_COMMAND"
 fi
 
 # dynamically set the  PS1
